name: Babiza FM 24/7 Radio

on:
  workflow_dispatch:

jobs:
  broadcast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get install -y ffmpeg

      - name: Shuffle and Broadcast
        run: |
          while true; do
            # 1. This finds EVERY mp3 and handles spaces/random names perfectly
            find . -name "*.mp3" -printf "file '%p'\n" | shuf > playlist.txt
            
            # 2. This streams that shuffled list to your Zeno station
            ffmpeg -re -f concat -safe 0 -i playlist.txt -f flv "rtmp://link.zeno.fm:80/fl9cqwh5b6ftv/JJq8xWfy"
          done
